#ifndef __XFSD_TRACE_H__
#define __XFSD_TRACE_H__

#define trace_xfs_readdir(dp)
#define trace_xfs_dir2_grow_inode(args, space)
#define trace_xfs_dir2_shrink_inode(args, db)
#define trace_xfs_dir2_block_addname(args)
#define trace_xfs_dir2_block_lookup(args)
#define trace_xfs_dir2_block_removename(args)
#define trace_xfs_dir2_block_replace(args)
#define trace_xfs_dir2_leaf_to_block(args)
#define trace_xfs_dir2_sf_to_block(args)
#define trace_xfs_dir2_block_to_leaf(args)
#define trace_xfs_dir2_leaf_addname(args)
#define trace_xfs_dir2_leaf_lookup(args)
#define trace_xfs_dir2_leaf_removename(args)
#define trace_xfs_dir2_leaf_replace(args)
#define trace_xfs_dir2_node_to_leaf(args)
#define trace_xfs_dir2_leaf_to_node(args)
#define trace_xfs_dir2_leafn_add(args, index)
#define trace_xfs_dir2_leafn_moveents(args, start_s, start_d, count)
#define trace_xfs_dir2_leafn_remove(args, index)
#define trace_xfs_dir2_node_addname(args)
#define trace_xfs_dir2_node_lookup(args)
#define trace_xfs_dir2_node_removename(args)
#define trace_xfs_dir2_node_replace(args)
#define trace_xfs_dir2_block_to_sf(args)
#define trace_xfs_dir2_sf_addname(args)
#define trace_xfs_dir2_sf_create(args)
#define trace_xfs_dir2_sf_lookup(args)
#define trace_xfs_dir2_sf_removename(args)
#define trace_xfs_dir2_sf_replace(args)
#define trace_xfs_dir2_sf_toino4(args)
#define trace_xfs_dir2_sf_toino8(args)

#define trace_xfs_get_acl(ip)
#define trace_xfs_btree_corrupt(bp, _RET_IP_)
#define trace_xfs_alloc_exact_done(args)
#define trace_xfs_alloc_exact_notfound(args)
#define trace_xfs_alloc_exact_error(args)
#define trace_xfs_alloc_near_noentry(args)
#define trace_xfs_alloc_near_nominleft(args)
#define trace_xfs_alloc_near_first(args)
#define trace_xfs_alloc_near_busy(args)
#define trace_xfs_alloc_size_neither(args)
#define trace_xfs_alloc_near_nominleft(args)
#define trace_xfs_alloc_near_greater(args)
#define trace_xfs_alloc_near_lesser(args)
#define trace_xfs_alloc_near_error(args)
#define trace_xfs_alloc_size_noentry(args)
#define trace_xfs_alloc_size_busy(args)
#define trace_xfs_alloc_size_busy(args)
#define trace_xfs_alloc_size_done(args)
#define trace_xfs_alloc_size_error(args)
#define trace_xfs_alloc_size_nominleft(args)
#define trace_xfs_alloc_small_freelist(args)
#define trace_xfs_alloc_small_notenough(args)
#define trace_xfs_alloc_small_done(args)
#define trace_xfs_alloc_small_error(args)
#define trace_xfs_free_extent(mp, agno, bno, len, isfl, haveleft, haveright)
#define trace_xfs_agf(t_mountp, bp, fields, _RET_IP_)
#define trace_xfs_alloc_vextent_badargs(args)
#define trace_xfs_alloc_vextent_nofix(args)
#define trace_xfs_alloc_vextent_noagbp(args)
#define trace_xfs_alloc_vextent_nofix(args)
#define trace_xfs_alloc_vextent_loopfailed(args)
#define trace_xfs_alloc_vextent_allfailed(args)
#define trace_xfs_setfilesize(ip, io_offset, io_size)
#define trace_xfs_map_blocks_alloc(ip, offset, count, type, imap)
#define trace_xfs_map_blocks_found(ip, offset, count, type, imap)
#define trace_xfs_invalidatepage(host, page, offset)
#define trace_xfs_writepage(inode, page, b)
#define trace_xfs_releasepage(host, page, b)
#define trace_xfs_get_blocks_alloc(ip, offset, size, b, imap)
#define trace_xfs_get_blocks_found(ip, offset, size, b, imap)
#define trace_xfs_get_blocks_notfound(ip, offset, size)
#define trace_xfs_vm_bmap(inode)
#define trace_xfs_attr_list_full(context)
#define trace_xfs_attr_list_add(context)
#define trace_xfs_attr_sf_addname(args)
#define trace_xfs_attr_leaf_addname(args)
#define trace_xfs_attr_leaf_replace(args)
#define trace_xfs_attr_leaf_removename(args)
#define trace_xfs_attr_leaf_get(args)
#define trace_xfs_attr_leaf_list(context)
#define trace_xfs_attr_node_addname(args)
#define trace_xfs_attr_node_replace(args)
#define trace_xfs_attr_node_removename(args)
#define trace_xfs_attr_fillstate(args)
#define trace_xfs_attr_refillstate(args)
#define trace_xfs_attr_node_get(args)
#define trace_xfs_attr_node_list(context)
#define trace_xfs_attr_list_wrong_blk(context)
#define trace_xfs_attr_list_wrong_blk(context)
#define trace_xfs_attr_list_wrong_blk(context)
#define trace_xfs_attr_list_wrong_blk(context)
#define trace_xfs_attr_list_node_descend(context, btree)
#define trace_xfs_attr_rmtval_get(args)
#define trace_xfs_attr_rmtval_set(args)
#define trace_xfs_attr_rmtval_remove(args)
#define trace_xfs_attr_sf_create(args)
#define trace_xfs_attr_sf_add(args)
#define trace_xfs_attr_sf_remove(args)
#define trace_xfs_attr_sf_lookup(args)
#define trace_xfs_attr_sf_to_leaf(args)
#define trace_xfs_attr_list_sf(context)
#define trace_xfs_attr_list_sf_all(context)
#define trace_xfs_attr_leaf_to_sf(args)
#define trace_xfs_attr_leaf_to_node(args)
#define trace_xfs_attr_leaf_create(args)
#define trace_xfs_attr_leaf_split(args)
#define trace_xfs_attr_leaf_add_old(args)
#define trace_xfs_attr_leaf_add_new(args)
#define trace_xfs_attr_leaf_add(args)
#define trace_xfs_attr_leaf_add_work(args)
#define trace_xfs_attr_leaf_compact(args)
#define trace_xfs_attr_leaf_rebalance(args)
#define trace_xfs_attr_leaf_toosmall(args)
#define trace_xfs_attr_leaf_remove(args)
#define trace_xfs_attr_leaf_unbalance(args)
#define trace_xfs_attr_leaf_lookup(args)
#define trace_xfs_attr_list_leaf(context)
#define trace_xfs_attr_list_notfound(context)
#define trace_xfs_attr_list_leaf_end(context)
#define trace_xfs_attr_leaf_clearflag(args)
#define trace_xfs_attr_leaf_setflag(args)
#define trace_xfs_attr_leaf_flipflags(args)
#define trace_xfs_btree_corrupt(bp, _RET_IP_)
#define trace_xfs_extlist(ip, idx, whichfork, caller_ip)
#define trace_xfs_bmap_pre_update(ip, idx, state, _THIS_IP_)
#define trace_xfs_bmap_post_update(ip, idx, state, _THIS_IP_)
#define trace_xfs_bunmap(ip, bno, len, flags, _RET_IP_)
#define trace_xfs_btree_corrupt(bp, _RET_IP_)
#define trace_xfs_btree_corrupt(bp, _RET_IP_)
#define trace_xfs_buf_init(bp, _RET_IP_)
#define trace_xfs_buf_free(bp, _RET_IP_)
#define trace_xfs_buf_find(bp, flags, _RET_IP_)
#define trace_xfs_buf_get(bp, flags, _RET_IP_)
#define trace_xfs_buf_read(bp, flags, _RET_IP_)
#define trace_xfs_buf_get_uncached(bp, _RET_IP_)
#define trace_xfs_buf_hold(bp, _RET_IP_)
#define trace_xfs_buf_rele(bp, _RET_IP_)
#define trace_xfs_buf_trylock(bp, _RET_IP_)
#define trace_xfs_buf_lock(bp, _RET_IP_)
#define trace_xfs_buf_lock_done(bp, _RET_IP_)
#define trace_xfs_buf_unlock(bp, _RET_IP_)
#define trace_xfs_buf_iodone(bp, _RET_IP_)
#define trace_xfs_buf_ioerror(bp, error, _RET_IP_)
#define trace_xfs_bdstrat_shut(bp, _RET_IP_)
#define trace_xfs_bdstrat_shut(bp, _RET_IP_)
#define trace_xfs_buf_iorequest(bp, _RET_IP_)
#define trace_xfs_buf_iowait(bp, _RET_IP_)
#define trace_xfs_buf_iowait_done(bp, _RET_IP_)
#define trace_xfs_buf_wait_buftarg(bp, _RET_IP_)
#define trace_xfs_buf_delwri_queued(bp, _RET_IP_)
#define trace_xfs_buf_delwri_queue(bp, _RET_IP_)
#define trace_xfs_buf_delwri_split(bp, _RET_IP_)
#define trace_xfs_buf_item_size_stale(bip)
#define trace_xfs_buf_item_size(bip)
#define trace_xfs_buf_item_format_stale(bip)
#define trace_xfs_buf_item_format(bip)
#define trace_xfs_buf_item_pin(bip)
#define trace_xfs_buf_item_unpin(bip)
#define trace_xfs_buf_item_unpin_stale(bip)
#define trace_xfs_buf_item_push(bip)
#define trace_xfs_buf_item_unlock_stale(bip)
#define trace_xfs_buf_item_unlock(bip)
#define trace_xfs_buf_item_committed(bip)
#define trace_xfs_buf_item_relse(bp, _RET_IP_)
#define trace_xfs_buf_item_iodone(bp, _RET_IP_)
#define trace_xfs_buf_item_iodone_async(bp, _RET_IP_)
#define trace_xfs_buf_error_relse(bp, _RET_IP_)
#define trace_xfs_da_node_create(args)
#define trace_xfs_da_split(args)
#define trace_xfs_attr_leaf_split_before(args)
#define trace_xfs_attr_leaf_split_after(args)
#define trace_xfs_da_root_split(args)
#define trace_xfs_da_node_split(args)
#define trace_xfs_da_node_rebalance(args)
#define trace_xfs_da_node_add(args)
#define trace_xfs_da_join(args)
#define trace_xfs_da_root_join(args)
#define trace_xfs_da_node_toosmall(args)
#define trace_xfs_da_fixhashpath(args)
#define trace_xfs_da_node_remove(args)
#define trace_xfs_da_node_unbalance(args)
#define trace_xfs_da_link_before(args)
#define trace_xfs_da_link_after(args)
#define trace_xfs_da_unlink_back(args)
#define trace_xfs_da_unlink_forward(args)
#define trace_xfs_da_path_shift(args)
#define trace_xfs_da_grow_inode(args)
#define trace_xfs_da_swap_lastblock(args)
#define trace_xfs_da_shrink_inode(args)
#define trace_xfs_da_btree_corrupt(bp, _RET_IP_)
#define trace_xfs_swap_extent_before(ip, b)
#define trace_xfs_swap_extent_after(ip, b)
#define trace_xfs_dir2_block_addname(args)
#define trace_xfs_dir2_block_lookup(args)
#define trace_xfs_dir2_block_removename(args)
#define trace_xfs_dir2_block_replace(args)
#define trace_xfs_dir2_leaf_to_block(args)
#define trace_xfs_dir2_sf_to_block(args)
#define trace_xfs_readdir(dp)
#define trace_xfs_dir2_grow_inode(args, space)
#define trace_xfs_dir2_shrink_inode(args, db)
#define trace_xfs_dir2_block_to_leaf(args)
#define trace_xfs_dir2_leaf_addname(args)
#define trace_xfs_dir2_leaf_lookup(args)
#define trace_xfs_dir2_leaf_removename(args)
#define trace_xfs_dir2_leaf_replace(args)
#define trace_xfs_dir2_node_to_leaf(args)
#define trace_xfs_dir2_leaf_to_node(args)
#define trace_xfs_dir2_leafn_add(args, index)
#define trace_xfs_dir2_leafn_moveents(args, start_s, start_d, count)
#define trace_xfs_dir2_leafn_remove(args, index)
#define trace_xfs_dir2_node_addname(args)
#define trace_xfs_dir2_node_lookup(args)
#define trace_xfs_dir2_node_removename(args)
#define trace_xfs_dir2_node_replace(args)
#define trace_xfs_dir2_block_to_sf(args)
#define trace_xfs_dir2_sf_addname(args)
#define trace_xfs_dir2_sf_create(args)
#define trace_xfs_dir2_sf_lookup(args)
#define trace_xfs_dir2_sf_removename(args)
#define trace_xfs_dir2_sf_replace(args)
#define trace_xfs_dir2_sf_toino4(args)
#define trace_xfs_dir2_sf_toino8(args)
#define trace_xfs_discard_toosmall(mp, agno, fbno, flen)
#define trace_xfs_discard_exclude(mp, agno, fbno, flen)
#define trace_xfs_discard_busy(mp, agno, fbno, flen)
#define trace_xfs_discard_extent(mp, agno, fbno, flen)
#define trace_xfs_dqalloc(dqp)
#define trace_xfs_dqtobp_read(dqp)
#define trace_xfs_dqread(dqp)
#define trace_xfs_dqread_fail(dqp)
#define trace_xfs_dqget_freeing(dqp)
#define trace_xfs_dqget_hit(dqp)
#define trace_xfs_dqget_dup(dqp)
#define trace_xfs_dqget_miss(dqp)
#define trace_xfs_dqput_free(dqp)
#define trace_xfs_dqput(dqp)
#define trace_xfs_dqrele(dqp)
#define trace_xfs_dqflush(dqp)
#define trace_xfs_dqflush_force(dqp)
#define trace_xfs_dqflush_done(dqp)
#define trace_xfs_extent_busy_enomem(t_mountp, agno, bno, len)
#define trace_xfs_extent_busy(t_mountp, agno, bno, len)
#define trace_xfs_extent_busy_reuse(mp, pag_agno, fbno, flen)
#define trace_xfs_extent_busy_force(mp, pag_agno, fbno, flen)
#define trace_xfs_extent_busy_trim(mp, agno, bno, len, fbno, b)
#define trace_xfs_extent_busy_clear(mp, agno, bno, length)
#define trace_xfs_dir_fsync(ip)
#define trace_xfs_file_fsync(ip)
#define trace_xfs_file_read(ip, size, pos, ioflags)
#define trace_xfs_file_splice_read(ip, count, ppos, ioflags)
#define trace_xfs_file_splice_write(ip, count, ppos, ioflags)
#define trace_xfs_file_direct_write(ip, count, ki_pos, b)
#define trace_xfs_file_buffered_write(ip, count, ki_pos, b)
#define trace_xfs_pagecache_inval(ip, first, last)
#define trace_xfs_btree_corrupt(bp, _RET_IP_)
#define trace_xfs_iget_skip(ip)
#define trace_xfs_iget_skip(ip)
#define trace_xfs_iget_reclaim(ip)
#define trace_xfs_iget_reclaim_fail(ip)
#define trace_xfs_iget_skip(ip)
#define trace_xfs_iget_hit(ip)
#define trace_xfs_iget_miss(ip)
#define trace_xfs_perag_set_reclaim(i_mount, pag_agno, a, _RET_IP_)
#define trace_xfs_perag_clear_reclaim(i_mount, pag_agno, a, _RET_IP_)
#define trace_xfs_inode_free_eofblocks_invalid(ip)
#define trace_xfs_inode_set_eofblocks_tag(ip)
#define trace_xfs_perag_set_eofblocks(i_mount, pag_agno, a, _RET_IP_)
#define trace_xfs_inode_clear_eofblocks_tag(ip)
#define trace_xfs_perag_clear_eofblocks(i_mount, pag_agno, a, _RET_IP_)
#define trace_xfs_iget_skip(ip)
#define trace_xfs_iget_skip(ip)
#define trace_xfs_iget_reclaim(ip)
#define trace_xfs_iget_reclaim_fail(ip)
#define trace_xfs_iget_skip(ip)
#define trace_xfs_iget_hit(ip)
#define trace_xfs_iget_miss(ip)
#define trace_xfs_ilock(ip, lock_flags, _RET_IP_)
#define trace_xfs_ilock_nowait(ip, lock_flags, _RET_IP_)
#define trace_xfs_iunlock(ip, lock_flags, _RET_IP_)
#define trace_xfs_ilock_demote(ip, lock_flags, _RET_IP_)
#define trace_xfs_ilock(ip, lock_flags, _RET_IP_)
#define trace_xfs_ilock_nowait(ip, lock_flags, _RET_IP_)
#define trace_xfs_iunlock(ip, lock_flags, _RET_IP_)
#define trace_xfs_ilock_demote(ip, lock_flags, _RET_IP_)
#define trace_xfs_itruncate_extents_start(ip, new_size)
#define trace_xfs_itruncate_extents_end(ip, new_size)
#define trace_xfs_inode_unpin_nowait(ip, _RET_IP_)
#define trace_xfs_iext_insert(ip, idx, new, state, _RET_IP_)
#define trace_xfs_iext_remove(ip, idx, state, _RET_IP_)
#define trace_xfs_ihold(ip, _THIS_IP_)
#define trace_xfs_irele(ip, _THIS_IP_)
#define trace_xfs_inode_pin(ip, _RET_IP_)
#define trace_xfs_inode_unpin(ip, _RET_IP_)
#define trace_xfs_file_compat_ioctl(ip)
#define trace_xfs_ioctl_setattr(ip)
#define trace_xfs_file_ioctl(ip)
#define trace_xfs_iomap_prealloc_size(ip, alloc_blocks, shift, m_writeio_blocks)
#define trace_xfs_delalloc_enospc(ip, offset, count)
#define trace_xfs_unwritten_convert(ip, offset, count)
#define trace_xfs_getattr(ip)
#define trace_xfs_setattr(ip)
#define trace_xfs_setattr(ip)
#define trace_xfs_update_time(ip)
#define trace_xfs_log_grant_wake_up(log, tic)
#define trace_xfs_log_grant_sleep(log, tic)
#define trace_xfs_log_grant_wake(log, tic)
#define trace_xfs_log_regrant(log, tic)
#define trace_xfs_log_regrant_exit(log, tic)
#define trace_xfs_log_reserve(log, tic)
#define trace_xfs_log_reserve_exit(log, tic)
#define trace_xfs_log_done_nonperm(log, ticket)
#define trace_xfs_log_done_perm(log, ticket)
#define trace_xfs_log_umount_write(log, tic)
#define trace_xfs_log_regrant_reserve_enter(log, ticket)
#define trace_xfs_log_regrant_reserve_sub(log, ticket)
#define trace_xfs_log_regrant_reserve_exit(log, ticket)
#define trace_xfs_log_ungrant_enter(log, ticket)
#define trace_xfs_log_ungrant_sub(log, ticket)
#define trace_xfs_log_ungrant_exit(log, ticket)
#define trace_xfs_log_force(mp, lsn)
#define trace_xfs_log_recover_item_add_cont(log, trans, item, b)
#define trace_xfs_log_recover_item_add(log, trans, item, b)
#define trace_xfs_log_recover_item_reorder_head(log, trans, item, pass)
#define trace_xfs_log_recover_item_reorder_tail(log, trans, item, pass)
#define trace_xfs_log_recover_buf_not_cancel(log, buf_f)
#define trace_xfs_log_recover_buf_cancel_ref_inc(log, buf_f)
#define trace_xfs_log_recover_buf_cancel_add(log, buf_f)
#define trace_xfs_log_recover_buf_inode_buf(m_log, buf_f)
#define trace_xfs_log_recover_buf_reg_buf(m_log, buf_f)
#define trace_xfs_log_recover_buf_dquot_buf(log, buf_f)
#define trace_xfs_log_recover_buf_cancel(log, buf_f)
#define trace_xfs_log_recover_buf_recover(log, buf_f)
#define trace_xfs_log_recover_inode_cancel(log, in_f)
#define trace_xfs_log_recover_inode_recover(log, in_f)
#define trace_xfs_log_recover_inode_skip(log, in_f)
#define trace_xfs_log_recover_item_recover(log, trans, item, XLOG_RECOVER_PASS2)
#define trace_xfs_perag_get(mp, agno, ref, _RET_IP_)
#define trace_xfs_perag_get_tag(mp, pag_agno, ref, _RET_IP_)
#define trace_xfs_perag_put(pag_mount, pag_agno, ref, _RET_IP_)
#define trace_xfs_dqattach_found(dqp)
#define trace_xfs_dqattach_get(dqp)
#define trace_xfs_dquot_dqdetach(ip)
#define trace_xfs_reset_dqcounts(bp, _RET_IP_)
#define trace_xfs_dqadjust(dqp)
#define trace_xfs_dqreclaim_want(dqp)
#define trace_xfs_dqreclaim_dirty(dqp)
#define trace_xfs_dqreclaim_done(dqp)
#define trace_xfs_dqreclaim_busy(dqp)
#define trace_xfs_dquot_dqalloc(ip)
#define trace_xfs_rename(src_dp, target_dp, src_name, target_name)
#define trace_xfs_destroy_inode(ip)
#define trace_xfs_evict_inode(ip)
#define trace_xfs_ail_push(lip)
#define trace_xfs_ail_flushing(lip)
#define trace_xfs_ail_pinned(lip)
#define trace_xfs_ail_locked(lip)
#define trace_xfs_trans_bjoin(b_fspriv)
#define trace_xfs_trans_get_buf_recur(bip)
#define trace_xfs_trans_get_buf(b_fspriv)
#define trace_xfs_trans_getsb_recur(bip)
#define trace_xfs_trans_getsb(b_fspriv)
#define trace_xfs_trans_read_buf_io(bp, _RET_IP_)
#define trace_xfs_trans_read_buf_shut(bp, _RET_IP_)
#define trace_xfs_trans_read_buf_recur(bip)
#define trace_xfs_trans_read_buf(b_fspriv)
#define trace_xfs_trans_read_buf_shut(bp, _RET_IP_)
#define trace_xfs_trans_brelse(bip)
#define trace_xfs_trans_bhold(bip)
#define trace_xfs_trans_bhold_release(bip)
#define trace_xfs_trans_log_buf(bip)
#define trace_xfs_trans_binval(bip)
#define trace_xfs_readlink(ip)
#define trace_xfs_lookup(dp, name)
#define trace_xfs_create(dp, name)
#define trace_xfs_remove(dp, name)
#define trace_xfs_link(tdp, target_name)
#define trace_xfs_symlink(dp, link_name)
#define trace_xfs_alloc_file_space(ip)
#define trace_xfs_free_file_space(ip)

#endif
