#ifndef __XFSD_TRACE_H__
#define __XFSD_TRACE_H__

#define trace_xfs_readdir(dp)
#define trace_xfs_dir2_grow_inode(args, space)
#define trace_xfs_dir2_shrink_inode(args, db)
#define trace_xfs_dir2_block_addname(args)
#define trace_xfs_dir2_block_lookup(args)
#define trace_xfs_dir2_block_removename(args)
#define trace_xfs_dir2_block_replace(args)
#define trace_xfs_dir2_leaf_to_block(args)
#define trace_xfs_dir2_sf_to_block(args)
#define trace_xfs_dir2_block_to_leaf(args)
#define trace_xfs_dir2_leaf_addname(args)
#define trace_xfs_dir2_leaf_lookup(args)
#define trace_xfs_dir2_leaf_removename(args)
#define trace_xfs_dir2_leaf_replace(args)
#define trace_xfs_dir2_node_to_leaf(args)
#define trace_xfs_dir2_leaf_to_node(args)
#define trace_xfs_dir2_leafn_add(args, index)
#define trace_xfs_dir2_leafn_moveents(args, start_s, start_d, count)
#define trace_xfs_dir2_leafn_remove(args, index)
#define trace_xfs_dir2_node_addname(args)
#define trace_xfs_dir2_node_lookup(args)
#define trace_xfs_dir2_node_removename(args)
#define trace_xfs_dir2_node_replace(args)
#define trace_xfs_dir2_block_to_sf(args)
#define trace_xfs_dir2_sf_addname(args)
#define trace_xfs_dir2_sf_create(args)
#define trace_xfs_dir2_sf_lookup(args)
#define trace_xfs_dir2_sf_removename(args)
#define trace_xfs_dir2_sf_replace(args)
#define trace_xfs_dir2_sf_toino4(args)
#define trace_xfs_dir2_sf_toino8(args)

#endif
